name: last_roadi_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  firebase_core: ^2.4.1
  get_storage: ^2.0.3
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.5.1
  cometchat_chat_uikit: ^4.0.0
  hexcolor: ^2.0.7
  introduction_screen: ^3.0.1
  dots_indicator: ^2.1.0
  google_fonts: ^4.0.0
  syncfusion_flutter_datepicker: ^20.4.54
  intl: ^0.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/image/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo.ttf
          weight: 400
        - asset: assets/font/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700
        - asset: assets/font/Cairo-Black.ttf
          weight: 900
